services:
    application:
        container_name: terms-module-chromium-bundle_app
        build: docker
        volumes:
            - .:/app:rw,cached
            - ~/.composer:/home/application/.composer:cached
            - ~/.ssh:/home/application/.ssh:cached
